name: lynxgaming
description: "Gaming app for customization games and tools"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.0
  android_intent_plus: ^5.3.0
  shared_preferences: ^2.5.3
  logger: ^2.5.0
  http: ^1.4.0
  flutter_v2ray: ^1.0.10
  dio: ^5.8.0+1
  archive: ^4.0.7
  flutter_query: ^0.3.7
  file_picker: ^10.1.8
  get: ^4.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
  #   - assets/images/
  #   - assets/icons/
  #   - assets/fonts/